services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  tests:
    build: ./backend
    container_name: backend_tests
    command: pytest -v
    depends_on:
      - postgres
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "5000:5000"

volumes:
  postgres_data: